name = "windsock"
version = "0.1.0"
description = "Socket.IO frame primitives for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "windsock" }
gleam = ">= 1.7.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.48.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
startest = ">= 0.8.0 and < 1.0.0"
